"type.definition" = { fg = "#56B7C3" }
"tag.attribute" = { fg = "#56B7C3" }
"markup.list.markdown" = { fg = "#56B7C3" }
"function.builtin" = { fg = "#6495EE" }
"function.method" = { fg = "#6495EE", modifiers = [ "bold" ] }
"function.method.call" = { fg = "#6495EE", modifiers = [ "bold" ] }
"function.macro" = { fg = "#6495EE", modifiers = [ "bold" ] }
"comment.todo" = { fg = "#6495EE" }
"local.definition.function" = { fg = "#6495EE", modifiers = [ "bold" ] }
"local.definition.method" = { fg = "#6495EE", modifiers = [ "bold" ] }
"markup.link.label" = { fg = "#6495EE" }
"punctuation.special" = { fg = "#6495EE" }
"constant" = { fg = "#FF9070" }
"constant.builtin" = { fg = "#FF9070" }
"constant.macro" = { fg = "#FF9070" }
"number.float" = { fg = "#FF9070" }
"local.definition.constant" = { fg = "#FF9070" }
"string.special" = { fg = "#FF9070" }
"keyword.import" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"keyword.coroutine" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"keyword.repeat" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"diagnostic.info" = { fg = "#00b7cb", bg = "#233e4b" }
"keyword.exception" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"keyword.conditional" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"keyword.conditional.ternary" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"keyword.operator" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"diagnostic.warning" = { fg = "#EF973A", bg = "#463D3A" }
"tag.xml" = { fg = "#E06C75" }
"tag" = { fg = "#E06C75" }
"tag.builtin" = { fg = "#E06C75" }
"variable.member" = { fg = "#E06C75" }
"diagnostic.error" = { fg = "#F36464", bg = "#3D3037" }
"local.definition.namespace" = { fg = "#E06C75" }
"local.definition.var" = { fg = "#B0B7C3" }
"variable.parameter" = { fg = "#E4BF7F" }
"variable.parameter.builtin" = { fg = "#E4BF7F" }
"local.definition.parameter" = { fg = "#E4BF7F" }
"string.regexp" = { fg = "#E4BF7F" }
"type.builtin" = { fg = "#FF6AB3" }
"label.markdown" = { fg = "#FF6AB3" }
"type" = { fg = "#56B7C3" }
"ui.linenr" = { fg = "#50567C" }
"ui.linenr.selected" = { fg = "#B0B7C3" }
"ui.text" = { fg = "#B0B7C3" }
"ui.cursor" = { bg = "#FF9070" }
"keyword.modifier" = { fg = "#A78CFA", modifiers = [ "bold" ] }
"ui.window" = { fg = "#8A97C3", bg = "#282C34" }
"ui.cursor.match" = { fg = "#FF9070" }
"label" = { fg = "#98C379" }
"string.special.path.diff" = { fg = "#98C379" }
"string.special.url" = { fg = "#98C379" }
"string.special.path" = { fg = "#98C379" }
"markup.raw" = { fg = "#98C379" }
"lsp.typemod.struct.builtin.nix" = { fg = "#FF9070" }
"function.builtin.nix" = { fg = "#6495EE" }
"lsp.typemod.constant.readonly.nix" = { fg = "#E06C75" }
"markup.link.url" = { fg = "#98C379", underline = true }
"string.documentation" = { fg = "#676E95", modifiers = [ "italic" ] }
"variable.member.lua" = { fg = "#E06C75" }
"function.macro.luadoc" = { fg = "#56B7C3" }
"constant.builtin.javascript" = { fg = "#CF68E1" }
"punctuation.special.javascript" = { fg = "#6495EE" }
"lsp.type.namespace.javascript" = { fg = "#E06C75" }
"comment.note" = { fg = "#598DEF" }
"comment.documentation" = { fg = "#676E95", modifiers = [ "italic" ] }
"function.builtin.powershell" = { fg = "#6495EE" }
"type.builtin.powershell" = { fg = "#FF6AB3" }
"variable.builtin.powershell" = { fg = "#E06C75" }
"variable.parameter.builtin.powershell" = { fg = "#C57BDB" }
"variable.parameter.powershell" = { fg = "#98C379" }
"lsp.type.keyword.ps1" = []
"lsp.type.operator.ps1" = []
"keyword.return.typescript" = { fg = "#CF68E1" }
"keyword.conditional.typescript" = { fg = "#CF68E1" }
"constant.builtin.typescript" = { fg = "#CF68E1" }
"lsp.type.namespace.typescript" = { fg = "#E06C75" }
"variable.member.typescript" = { fg = "#E06C75" }
"constructor.typescript" = { fg = "#6495EE" }
"punctuation.special.typescript" = { fg = "#6495EE" }
"lsp.typemod.variable.defaultLibrary.typescript" = { fg = "#FF9070" }
"string.escape" = { fg = "#8A97C3" }
"markup" = { fg = "#838FA7" }
"string.special.url.html" = { fg = "#98C379" }
"markup.link.label.html" = { fg = "#98C379" }
"tag.delimiter.html" = { fg = "#838FA7" }
"markup.heading.html" = { fg = "#B0B7C3" }
"variable.css" = { fg = "#E4BF7F" }
"keyword.modifier.css" = { fg = "#F02B77" }
"type.css" = { fg = "#98C379" }
"property.css" = { fg = "#8A97C3" }
"operator.css" = { fg = "#838FA7" }
"keyword.return.lua" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"markup.link" = { fg = "#98C379", underline = true }
"character" = { fg = "#98C379" }
"lsp.type.parameter" = { fg = "#E4BF7F" }
"lsp.type.property" = { fg = "#E06C75" }
"lsp.type.typeParameter" = { fg = "#E4BF7F" }
"keyword.control" = { fg = "#CF68E1" }
"keyword.return" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"comment.warning" = { fg = "#EF973A" }
"lsp.typemod.variable.definition.lua" = { fg = "#F02B77", modifiers = [ "bold" ] }
"comment.error" = { fg = "#F36464" }
"markup.strong" = { fg = "#E4BF7F", modifiers = [ "bold" ] }
"markup.raw.block.markdown" = { fg = "#8792AA" }
"punctuation.bracket.luadoc" = { fg = "#838FA7" }
"punctuation.bracket.lua" = { fg = "#838FA7" }
"constructor.lua" = { fg = "#838FA7" }
"punctuation.special.luadoc" = { fg = "#838FA7" }
"function.builtin.bash" = { fg = "#6495EE" }
"punctuation.special.bash" = { fg = "#6495EE" }
"variable.builtin.bash" = { fg = "#E06C75" }
"variable.parameter.bash" = { fg = "#98C379" }
"lsp.type.macro.lua" = { fg = "#56B7C3" }
"constant.builtin.lua" = { fg = "#CF68E1" }
"keyword.repeat.lua" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"function.builtin.lua" = { fg = "#6495EE" }
"lsp.type.parameter.lua" = { fg = "#E4BF7F" }
"function" = { fg = "#6495EE", modifiers = [ "bold" ] }
"operator" = { fg = "#56B7C3" }
"boolean" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"property" = { fg = "#E06C75" }
"comment" = { fg = "#676E95", modifiers = [ "italic" ] }
"diagnostic.hint" = { bg = "#343744", fg = "#50567C" }
"ui.statusline" = { bg = "#2F323C", fg = "#B0B7C3" }
"ui.text.focus" = { bg = "#2F3F5C", fg = "#D7DAE0" }
"ui.menu.selected" = { bg = "#2F3F5C", fg = "#D7DAE0" }
"ui.text.info" = { bg = "#21252b", fg = "#B0B7C3" }
"ui.menu" = { bg = "#21252b", fg = "#B0B7C3" }
"punctuation.bracket" = { fg = "#838FA7" }
"lsp.mod.defaultLibrary.lua" = { fg = "#FF9070" }
"markup.italic" = { fg = "#C57BDB", modifiers = [ "italic" ] }
"module" = { fg = "#E06C75" }
"markup.heading.6" = { fg = "#E06C75" }
"markup.heading.5" = { fg = "#E06C75" }
"markup.heading.4" = { fg = "#E06C75" }
"markup.heading.3" = { fg = "#E06C75" }
"markup.heading.2" = { fg = "#E06C75" }
"markup.heading.1" = { fg = "#E06C75" }
"markup.heading" = { fg = "#E06C75" }
"diff.delta" = { fg = "#A78CFA" }
"diff.plus" = { fg = "#40AD41" }
"diff.plus.diff" = { fg = "#40AD41" }
"diff.minus" = { fg = "#F14C4C" }
"diff.minus.diff" = { fg = "#F14C4C" }
"character.special" = { fg = "#8A97C3" }
"string.special.url.vue" = { fg = "#98C379" }
"tag.delimiter.vue" = { fg = "#838FA7" }
"ui.cursorline.primary" = { bg = "#2F323C", fg = "#B0B7C3" }
"diagnostic.unnecessary" = { fg = "#50567C" }
"punctuation" = { fg = "#838FA7" }
"ui.selection" = { bg = "#394E75" }
"punctuation.delimiter" = { fg = "#676E95" }
"string" = { fg = "#98C379" }
"module.builtin" = { fg = "#F02B77" }
"variable.builtin" = { fg = "#F02B77", modifiers = [ "bold" ] }
"keyword.type" = { fg = "#A78CFA", modifiers = [ "bold" ] }
"keyword.function" = { fg = "#A78CFA", modifiers = [ "bold" ] }
"keyword" = { fg = "#A78CFA", modifiers = [ "bold" ] }
"namespace.builtin" = { fg = "#A78CFA", modifiers = [ "bold" ] }
"keyword.directive.define" = { fg = "#A78CFA", modifiers = [ "bold" ] }
"variable.other.member" = { fg = "#E06C75" }
"ui.background" = { bg = "#282C34" }
"keyword.control.return" = { fg = "#CF68E1" }
"number" = { fg = "#FF9070" }
"ui.virtual.inlay-hint" = { fg = "#8A97C3", bg = "#343744" }
"module.c_sharp" = { fg = "#E06C75" }
"keyword.return.c" = { fg = "#CF68E1" }
"keyword.conditional.c" = { fg = "#CF68E1" }
"keyword.repeat.c" = { fg = "#CF68E1" }
"variable" = { fg = "#B0B7C3" }
"lsp.type.namespace.cs" = { fg = "#E06C75" }
"keyword.conditional.c_sharp" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"constant.builtin.c_sharp" = { fg = "#CF68E1" }
"lsp.type.enum.cs" = { fg = "#B0B7C3" }
"variable.builtin.vim" = { fg = "#E06C75" }
"markup.list" = { fg = "#98C379" }
"module.builtin.fsharp" = { fg = "#56B7C3" }
"variable_parameter.fsharp" = { fg = "#E4BF7F" }
"markup.raw.block" = { fg = "#98C379" }
"tag.delimiter.xml" = { fg = "#838FA7" }
"keyword.conditional.lua" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"lsp.typemod.function.defaultLibrary.lua" = { fg = "#6495EE", modifiers = [ "bold" ] }
"lsp.type.property.lua" = []
"lsp.type.variable.lua" = []
"string.regexp.lua" = { fg = "#98C379" }
"lsp.typemod.keyword.controlFlow.rust" = { fg = "#CF68E1", modifiers = [ "bold" ] }
"lsp.type.builtinType.rust" = { fg = "#FF6AB3" }
"lsp.type.typeAlias.rust" = { fg = "#56B7C3" }
"module.rust" = { fg = "#E06C75" }
"attribute" = { fg = "#56B7C3" }
"attribute.builtin" = { fg = "#56B7C3" }
"constructor" = { fg = "#56B7C3", modifiers = [ "bold" ] }
