"keyword.function" = { fg = "#A78CFA" }
"keyword.type" = { fg = "#A78CFA" }
"keyword.modifier" = { fg = "#A78CFA" }
"keyword.operator" = { fg = "#A78CFA" }
"type.builtin" = { fg = "#FF6AB3" }
"label.markdown" = { fg = "#FF6AB3" }
"variable.parameter.builtin" = { fg = "#E4BF7F" }
"local.definition.parameter" = { fg = "#E4BF7F" }
"string.regexp" = { fg = "#E4BF7F" }
"local.definition.var" = { fg = "#B0B7C3" }
"tag.xml" = { fg = "#E06C75" }
"tag.builtin" = { fg = "#E06C75" }
"local.definition.namespace" = { fg = "#E06C75" }
"attribute" = { fg = "#56B7C3" }
"punctuation.bracket" = { fg = "#838FA7" }
"punctuation.delimiter" = { fg = "#838FA7" }
"punctuation.special" = { fg = "#838FA7" }
"keyword.import" = { fg = "#CF68E1" }
"keyword.coroutine" = { fg = "#CF68E1" }
"keyword.repeat" = { fg = "#CF68E1" }
"keyword.return" = { fg = "#CF68E1" }
"keyword.exception" = { fg = "#CF68E1" }
"keyword.conditional" = { fg = "#CF68E1" }
"keyword.conditional.ternary" = { fg = "#CF68E1" }
"constant.builtin" = { fg = "#FF9070" }
"constant.macro" = { fg = "#FF9070" }
"function.builtin.powershell" = { fg = "#6495EE" }
"local.definition.constant" = { fg = "#FF9070" }
"function.method" = { fg = "#6495EE" }
"function.method.call" = { fg = "#6495EE" }
"function.macro" = { fg = "#6495EE" }
"comment.todo" = { fg = "#6495EE" }
"local.definition.function" = { fg = "#6495EE" }
"local.definition.method" = { fg = "#6495EE" }
"markup.link.label" = { fg = "#6495EE" }
"function.builtin.nix" = { fg = "#6495EE" }
"module.c_sharp" = { fg = "#E06C75" }
"markup.heading" = { fg = "#E06C75" }
"markup.heading.2" = { fg = "#E06C75" }
"markup.heading.3" = { fg = "#E06C75" }
"markup.heading.4" = { fg = "#E06C75" }
"markup.heading.5" = { fg = "#E06C75" }
"markup.heading.6" = { fg = "#E06C75" }
"diff.delta" = { fg = "#A78CFA" }
"markup.strong" = { fg = "#E4BF7F", modifiers = [ "bold" ] }
"markup.raw.block.markdown" = { fg = "#8792AA" }
"string.special.url.html" = { fg = "#98C379" }
"tag.delimiter.html" = { fg = "#838FA7" }
"variable.parameter" = { fg = "#E4BF7F" }
"comment.warning" = { fg = "#EF973A" }
"keyword.return.typescript" = { fg = "#CF68E1" }
"markup.list.markdown" = { fg = "#56B7C3" }
"tag.attribute" = { fg = "#56B7C3" }
"type.definition" = { fg = "#56B7C3" }
"constant.builtin.typescript" = { fg = "#CF68E1" }
"keyword.conditional.typescript" = { fg = "#CF68E1" }
"variable.member.typescript" = { fg = "#E06C75" }
"lsp.type.namespace.typescript" = { fg = "#E06C75" }
"number.float" = { fg = "#FF9070" }
"markup.raw.block" = { fg = "#98C379" }
"markup.raw" = { fg = "#98C379" }
"ui.cursorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr" = { fg = "#838FA7" }
"string.special.path" = { fg = "#98C379" }
"comment.error" = { fg = "#F36464" }
"constructor" = { fg = "#56B7C3" }
"operator" = { fg = "#838FA7" }
"property" = { fg = "#E06C75" }
"lsp.type.property.lua" = []
"lsp.typemod.variable.definition.lua" = { fg = "#F02B77" }
"lsp.mod.defaultLibrary.lua" = { fg = "#FF9070" }
"variable.member.lua" = { fg = "#E06C75" }
"function.builtin.lua" = { fg = "#6495EE" }
"lsp.typemod.function.defaultLibrary.lua" = { fg = "#6495EE" }
"lsp.type.parameter.lua" = { fg = "#E4BF7F" }
"punctuation.bracket.luadoc" = { fg = "#838FA7" }
"punctuation.bracket.lua" = { fg = "#838FA7" }
"constructor.lua" = { fg = "#838FA7" }
"punctuation.special.luadoc" = { fg = "#838FA7" }
"function.macro.luadoc" = { fg = "#56B7C3" }
"lsp.type.macro.lua" = { fg = "#56B7C3" }
"keyword.conditional.lua" = { fg = "#CF68E1" }
"keyword.repeat.lua" = { fg = "#CF68E1" }
"keyword.return.lua" = { fg = "#CF68E1" }
"keyword.operator.lua" = { fg = "#CF68E1" }
"constant.builtin.lua" = { fg = "#CF68E1" }
"module.rust" = { fg = "#E06C75" }
"lsp.type.typeAlias.rust" = { fg = "#56B7C3" }
"lsp.type.builtinType.rust" = { fg = "#FF6AB3" }
"lsp.typemod.keyword.controlFlow.rust" = { fg = "#CF68E1" }
"lsp.type.namespace.javascript" = { fg = "#E06C75" }
"keyword.operator.javascript" = { fg = "#A78CFA" }
"punctuation.special.javascript" = { fg = "#6495EE" }
"constant.builtin.javascript" = { fg = "#CF68E1" }
"lsp.typemod.variable.defaultLibrary.typescript" = { fg = "#FF9070" }
"punctuation.special.typescript" = { fg = "#6495EE" }
"constructor.typescript" = { fg = "#6495EE" }
"lsp.type.typeParameter" = { fg = "#56B7C3" }
"lsp.type.property" = { fg = "#E06C75" }
"lsp.type.parameter" = { fg = "#E4BF7F" }
"function.builtin.bash" = { fg = "#6495EE" }
"string.special.url.vue" = { fg = "#98C379" }
"tag.delimiter.vue" = { fg = "#838FA7" }
"keyword.return.c" = { fg = "#CF68E1" }
"keyword.conditional.c" = { fg = "#CF68E1" }
"keyword.repeat.c" = { fg = "#CF68E1" }
"tag.delimiter.xml" = { fg = "#838FA7" }
"lsp.type.enum.cs" = { fg = "#B0B7C3" }
"keyword.conditional.c_sharp" = { fg = "#CF68E1" }
"constant.builtin.c_sharp" = { fg = "#CF68E1" }
"lsp.typemod.constant.readonly.nix" = { fg = "#E06C75" }
"lsp.type.namespace.cs" = { fg = "#E06C75" }
"lsp.typemod.struct.builtin.nix" = { fg = "#FF9070" }
"variable_parameter.fsharp" = { fg = "#E4BF7F" }
"module.builtin.fsharp" = { fg = "#56B7C3" }
"variable.member" = { fg = "#E06C75" }
"markup.heading.1" = { fg = "#E06C75" }
"diff.plus.diff" = { fg = "#40AD41" }
"diff.minus.diff" = { fg = "#F14C4C" }
"string.escape" = { fg = "#8A97C3" }
"character.special" = { fg = "#8A97C3" }
"comment.documentation" = { fg = "#676E95", modifiers = [ "italic" ] }
"comment.note" = { fg = "#598DEF" }
"string.documentation" = { fg = "#676E95" }
"string.special.path.diff" = { fg = "#98C379" }
"string.special.url" = { fg = "#98C379" }
"markup.list" = { fg = "#98C379" }
"variable.builtin" = { fg = "#F02B77" }
"module.builtin" = { fg = "#F02B77" }
"keyword.directive.define" = { fg = "#A78CFA" }
"namespace.builtin" = { fg = "#A78CFA" }
"function" = { fg = "#6495EE" }
"constant" = { fg = "#FF9070" }
"label" = { fg = "#98C379" }
"string" = { fg = "#98C379" }
"markup.link.url" = { fg = "#98C379" }
"keyword" = { fg = "#A78CFA" }
"variable" = { fg = "#B0B7C3" }
"tag" = { fg = "#E06C75" }
"markup.italic" = { fg = "#C57BDB", modifiers = [ "italic" ] }
"boolean" = { fg = "#CF68E1" }
"number" = { fg = "#FF9070" }
