name: Update Submodule and Regenerate Files

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the job every day at midnight UTC

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Recursively update submodules

      - name: Install Neovim Latest Stable
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git add .

      - name: Regenerate Files
        run: |
          nvim --headless -c 'luafile generate.lua' -c 'qa'
          git add .

      - name: Commit changes
        run: |
          git commit -m "Automated update and file regeneration" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main

